// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type FilterNameStringType string

const (
	FilterNameStringType_all            FilterNameStringType = "all"
	FilterNameStringType_description    FilterNameStringType = "description"
	FilterNameStringType_name           FilterNameStringType = "name"
	FilterNameStringType_owning_service FilterNameStringType = "owning-service"
	FilterNameStringType_primary_region FilterNameStringType = "primary-region"
	FilterNameStringType_tag_key        FilterNameStringType = "tag-key"
	FilterNameStringType_tag_value      FilterNameStringType = "tag-value"
)

type SortOrderType string

const (
	SortOrderType_asc  SortOrderType = "asc"
	SortOrderType_desc SortOrderType = "desc"
)

type StatusType string

const (
	StatusType_Failed     StatusType = "Failed"
	StatusType_InProgress StatusType = "InProgress"
	StatusType_InSync     StatusType = "InSync"
)
